server:
  port: 8080
  trustedPort: 9003
  trustedPathPrefix: /internal/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ENC(KqcqXFaMiEBXIlgvGEb0wA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
jasypt:
  encryptor:
    #这里可以理解成是加解密的时候使用的密钥
    password: wlecyil