server:
  port: 8843
  # 配置https
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store-password: changeit
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS
  servlet:
    context-path: /dev
    session:
      timeout: 30m
  error:
    path: /error
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    basedir: C:\Program Files\Apache Software Foundation\Tomcat 9.0\temp
# 配置自定义属性
music:
  name: music003
  artist: aaa
  playCount: 30000
  description: ${music.name} by ${music.artist}
  comments[0]: good
  comments[1]: nice
  comments[2]: excellent
  rank:
    january: 1
    february: 1
    march: 2



