server:
  port: 8081
spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: 1987153442@qq.com
    password: amzrmmkovtnkjibf
    default-encoding: UTF-8

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(ilwRFkN3mzAdt9xycTPn/w==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
jasypt:
    encryptor:
      #这里可以理解成是加解密的时候使用的密钥
      password: wlecyil